apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-hostpath
  labels:
    type: local
spec:
  storageClassName: mysql-hostpath
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/e/k8s-vol/mysql-hostpath"
    type: DirectoryOrCreate
