apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: exampledb
  MYSQL_USER: exampleuser
  MYSQL_PASSWORD: examplepass