apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-hostpath
  labels:
    type: local
spec:
  storageClassName: wordpress-hostpath
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi 
  accessModes:  
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/e/k8s-vol/wordpress-hostpath"
    type: DirectoryOrCreate
