apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-hostpath
spec:
  storageClassName: wordpress-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 