apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-log-hostpath
  labels:
    type: local
spec:
  storageClassName: nginx-log-hostpath 
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi 
  accessModes:  
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/e/k8s-vol/nginx-log-hostpath"
    type: DirectoryOrCreate
